Format shell scripts (#27)
* Add check
* Format shell scripts
* Add make target
* Remove extra newline

diff --git a/root/usr/bin/fs-snapshot b/root/usr/bin/fs-snapshot
--- a/root/usr/bin/fs-snapshot
+++ b/root/usr/bin/fs-snapshot
@@ -6,8 +6,7 @@ color_gray='\e[7m'
 color_end='\e[m'
 target_filesystem=(/opt /var/cache /var/lib/docker)
 
-function mount_filesystem()
-{
+function mount_filesystem() {
   local _file_system=$1
   local _tmp_mount_point=$2
   local _top_level_subvolume=$3
@@ -21,8 +20,7 @@ function mount_filesystem()
   }
 }
 
-function umount_filesystem()
-{
+function umount_filesystem() {
   local _file_system=$1
   local _tmp_mount_point=$2
   local _top_level_subvolume=$3
@@ -35,8 +33,7 @@ function umount_filesystem()
   }
 }
 
-function list_snapshot()
-{
+function list_snapshot() {
   local _count_snapshot
   local _top_level_subvolume=$1
   local _file_system=$2
@@ -54,8 +51,7 @@ function list_snapshot()
   umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
 }
 
-function take_snapshot()
-{
+function take_snapshot() {
   local _top_level_subvolume=$1
   local _file_system=$2
   local _tmp_mount_point=/mnt/btrfs_$1
@@ -74,8 +70,7 @@ function take_snapshot()
   umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
 }
 
-function select_snapshot()
-{
+function select_snapshot() {
   local _key _key_prefix _key_suffix _snapshot _read_snapshot _line _arg _count_snapshot _current_rollback_snapshot
   local _top_level_subvolume=$1
   local _file_system=$2
@@ -86,33 +81,31 @@ function select_snapshot()
     return 1
   }
   _count_snapshot=0
-  while read _line
-  do
+  while read _line; do
     _snapshot[$_count_snapshot]="${_line}"
     ((_count_snapshot++))
   done < <(ls ${_tmp_mount_point} | awk --assign subvol_top="${_top_level_subvolume}" 'match($0, "^"subvol_top".")')
-  if [ ${_count_snapshot} -eq 0 ];then
+  if [ ${_count_snapshot} -eq 0 ]; then
     echo -e "${color_red}No snapshot. Take snapshot to rollback before select\nReturn menu${color_end}"
     umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
     return 1
   fi
 
   _count_snapshot=0
-  while read _line
-  do
+  while read _line; do
     _current_rollback_snapshot[$_count_snapshot]="${_line}"
     ((_count_snapshot++))
   done < <(ls ${_tmp_mount_point} | awk 'match($0, /^@/)')
-  if [ ${_count_snapshot} -eq 0 ];then
+  if [ ${_count_snapshot} -eq 0 ]; then
     echo -e "No current snapshot to rollback"
-  elif [ ${_count_snapshot} -eq 1 ];then
+  elif [ ${_count_snapshot} -eq 1 ]; then
     echo -e "Current snapshot to rollback is '${_current_rollback_snapshot}'"
     mv ${_tmp_mount_point}/${_current_rollback_snapshot} ${_tmp_mount_point}/${_current_rollback_snapshot#\@} || {
       echo "Failed to load current snapshot"
       umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
       return 1
     }
-  elif [ ${_count_snapshot} -ge 2 ];then
+  elif [ ${_count_snapshot} -ge 2 ]; then
     ls ${_tmp_mount_point} | awk 'match($0, /^@/)'
     echo -e "${color_red}Current snapshot is not one.\nAn error has occuerred.\nReturn menu${color_end}"
     umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
@@ -121,10 +114,8 @@ function select_snapshot()
 
   echo -e "[Select snapshot] cursor keys(up,down)\n[Return menu] 0\n"
   local _cursor=0
-  while :
-  do
-    for _read_snapshot in "${_snapshot[@]}"
-    do
+  while :; do
+    for _read_snapshot in "${_snapshot[@]}"; do
       if [ "${_snapshot[$_cursor]}" == "$_read_snapshot" ]; then
         echo -e " ${color_gray}$_read_snapshot${color_end}"
       else
@@ -140,20 +131,23 @@ function select_snapshot()
 
     _key+=${_key_prefix}${_key_suffix}
     case ${_key} in
-      $'\e[A') ((_cursor > 0)) && ((_cursor--))
-               ;;
-      $'\e[B') ((_cursor < ${#_snapshot[@]}-1)) && ((_cursor++))
-               ;;
-      0) clear
-         echo -e "Return main menu....\nUndo currenct snapshot to rollback"
-         mv ${_tmp_mount_point}/${_current_rollback_snapshot#\@} ${_tmp_mount_point}/${_current_rollback_snapshot} || {
-           echo "Faild to undo loading of current snapshot"
-           umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
-           return 1
-         }
-         sleep 3
-         break
-         ;;
+      $'\e[A')
+        ((_cursor > 0)) && ((_cursor--))
+        ;;
+      $'\e[B')
+        ((_cursor < ${#_snapshot[@]} - 1)) && ((_cursor++))
+        ;;
+      0)
+        clear
+        echo -e "Return main menu....\nUndo currenct snapshot to rollback"
+        mv ${_tmp_mount_point}/${_current_rollback_snapshot#\@} ${_tmp_mount_point}/${_current_rollback_snapshot} || {
+          echo "Faild to undo loading of current snapshot"
+          umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
+          return 1
+        }
+        sleep 3
+        break
+        ;;
     esac
     printf " \e[${#_snapshot[@]}A\e[m"
   done
@@ -174,78 +168,82 @@ function select_snapshot()
   umount_filesystem ${_file_system} ${_tmp_mount_point} ${_top_level_subvolume} || return 1
 }
 
-function menu_fs_list()
-{
+function menu_fs_list() {
   echo -e "\n[L] Show snapshot list\n[T] Take snapshot list\n[S] Select snapshot to boot\n[0] back main menu"
 }
 
-function menu_select_fs_list()
-{
+function menu_select_fs_list() {
   echo -e "\n[O] /opt\n[C] /var/cache\n[D] /var/lib/docker\n[Q] Quit"
 }
 
-function menu_fs()
-{
+function menu_fs() {
   echo -e "-----------------------------------------\n'$1' filesystem Manage\n-----------------------------------------"
   menu_fs_list
-  while :
-  do
+  while :; do
     local _key
     local _top_level_subvolume=$1
     local _file_system=$2
     read -p "> " _key
     case ${_key} in
-      L) clear
-         echo -e "---------------------------------------\nShow snapshot list\n---------------------------------------"
-         list_snapshot ${_top_level_subvolume} ${_file_system} || echo -e "${color_red}Can not read snapshot!${color_end}"
-         menu_fs_list
-         ;;
-      T) clear
-         echo -e "---------------------------------------\nTake snapshot\n---------------------------------------"
-         take_snapshot ${_top_level_subvolume} ${_file_system} || echo -e "${color_red}Can not take snapshot!${color_end}"
-         menu_fs_list
-         ;;
-      S) clear
-         echo -e "---------------------------------------\nSelect snapshot to rollback\n---------------------------------------"
-         select_snapshot ${_top_level_subvolume} ${_file_system} || echo -e "${color_red}Can not select snapshot!${color_end}"
-         menu_fs_list
-         ;;
-      0) echo "Back main menu"
-         menu_main
-         ;;
-      *) echo -e "${color_red}Unrecognized input${color_end}"
-         menu_fs_list
-         ;;
+      L)
+        clear
+        echo -e "---------------------------------------\nShow snapshot list\n---------------------------------------"
+        list_snapshot ${_top_level_subvolume} ${_file_system} || echo -e "${color_red}Can not read snapshot!${color_end}"
+        menu_fs_list
+        ;;
+      T)
+        clear
+        echo -e "---------------------------------------\nTake snapshot\n---------------------------------------"
+        take_snapshot ${_top_level_subvolume} ${_file_system} || echo -e "${color_red}Can not take snapshot!${color_end}"
+        menu_fs_list
+        ;;
+      S)
+        clear
+        echo -e "---------------------------------------\nSelect snapshot to rollback\n---------------------------------------"
+        select_snapshot ${_top_level_subvolume} ${_file_system} || echo -e "${color_red}Can not select snapshot!${color_end}"
+        menu_fs_list
+        ;;
+      0)
+        echo "Back main menu"
+        menu_main
+        ;;
+      *)
+        echo -e "${color_red}Unrecognized input${color_end}"
+        menu_fs_list
+        ;;
     esac
   done
 }
 
-function menu_main()
-{
+function menu_main() {
   clear
   echo -e "---------------------------------------\nUtility for manage filesystem snapshot\n---------------------------------------"
   menu_select_fs_list
-  while :
-  do
+  while :; do
     local _key
     read -p "> " _key
     case ${_key} in
-      O) clear
-         menu_fs opt /opt
-         ;;
-      C) clear
-         menu_fs var_cache /var/cache
-         ;;
-      D) clear
-         menu_fs var_lib_docker /var/lib/docker
-         ;;
-      Q) echo "Quit"
-         systemctl start docker.service || exit 1
-         exit 0
-         ;;
-      *) echo -e "${color_red}Unrecognized input${color_end}"
-         menu_select_fs_list
-         ;;
+      O)
+        clear
+        menu_fs opt /opt
+        ;;
+      C)
+        clear
+        menu_fs var_cache /var/cache
+        ;;
+      D)
+        clear
+        menu_fs var_lib_docker /var/lib/docker
+        ;;
+      Q)
+        echo "Quit"
+        systemctl start docker.service || exit 1
+        exit 0
+        ;;
+      *)
+        echo -e "${color_red}Unrecognized input${color_end}"
+        menu_select_fs_list
+        ;;
     esac
   done
 }
@@ -255,14 +253,13 @@ if [ "$EUID" -ne 0 ]; then
   exit 1
 fi
 
-for filesystem in "${target_filesystem[@]}"
-do
-  cat /etc/fstab | grep "${filesystem}" > /dev/null 2>&1
+for filesystem in "${target_filesystem[@]}"; do
+  cat /etc/fstab | grep "${filesystem}" >/dev/null 2>&1
   if [ $? -ne 0 ]; then
     echo -e "${filesystem} filesystem does not exist"
     exit 1
   fi
-  mount -l -t btrfs | grep "${filesystem}" > /dev/null 2>&1
+  mount -l -t btrfs | grep "${filesystem}" >/dev/null 2>&1
   if [ $? -ne 0 ]; then
     echo -e "${filesystem} filesystem is not mounted\n${color_red}Required file system is not mounted${color_end}"
     exit 1
